[tool.poetry]
name = "toja"
version = "1.0.0b1"
description = "The Old Joke Archive"
authors = ["Mark Hall <mark.hall@work.room3b.eu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.0.0"
cerberus = "^1.3.2"
email-validator = "^1.1.1"
pillow = "^8.1.1"
tesserocr = "^2.5.1"
PyYAML = "^5.4.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
flake8-print = "^3.1.4"
pre-commit = "^2.7.1"
tox = "^3.20.1"

[tool.poetry.extras]
postgresql = ["psycopg2"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
