version: "3.9"
services:
  couchdb:
    image: couchdb:3
    environment:
      COUCHDB_USER: main
      COUCHDB_PASSWORD: ohchieM0iefeuto5
    ports:
      - "127.0.0.1:5984:5984"
    volumes:
      - couchdb:/opt/couchdb/data
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "127.0.0.1:1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto_password_file:/mosquitto/config/password_file
  meilisearch:
    image: getmeili/meilisearch:v0.27.2
    environment:
      MEILI_MASTER_KEY: tho4shoochah4chaimue4aShi5aijac9
      ENV: development
      MEILI_NO_ANALYTICS: "true"
    ports:
      - "127.0.0.1:7700:7700"
    volumes:
      - meilisearch:/var/solr
volumes:
  couchdb:
  meilisearch:
