name: Docker Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy-secure:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Branch name
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

    - name: Build and push the scmmmh/oldjokearchive image
      uses: docker/build-push-action@v1.1.0
      with:
        username: scmmmh
        password: ${{ secrets.DOCKERACCESSTOKEN }}
        context: docker
        repository: scmmmh/oldjokearchive
        tags: ${{ steps.branch_name.outputs.SOURCE_TAG }}
        tag_with_sha: true
        dockerfile: binder/Dockerfile
