name: Docker Deployment

on:
  push:
    branches: [hatch-switch]
    tags:
      - "v*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      #- name: Branch name
      #  id: branch_name
      #  run: |
      #    echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
      #    echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
      #    echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/v}

      - name: Install Base Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-venv
          pip install hatch

      - name: Build Application
        run: |
          cd toja/server/frontend
          npm install
          npm run build
          cd ../../../
          hatch build
          cp dist/*.whl production/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: scmmmh
          password: ${{ secrets.DOCKERACCESSTOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: production
          push: false
          #tags: scmmmh/oldjokearchive:${{ steps.branch_name.outputs.SOURCE_TAG }}
