name: End-to-End Tests

on:
  push:
    branches: [ default, testcafe-switch ]
  pull_request:
    branches: [ default ]

jobs:
  e2e-test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Add .local path
      run: |
        echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
        echo "PIPX_BIN_DIR=$HOME/.local/bin" >> $GITHUB_ENV

    - name: Install Base Dependencies
      run: |
        sudo apt-get install python3-venv pipx
        pipx install poetry

    - name: Install Yarn Dependencies
      uses: CultureHQ/actions-yarn@master
      with:
        args: install

    - name: Install Python Dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry install

    - name: Run Tests
      run: |
        poetry config virtualenvs.in-project true
        poetry run test-server.sh &
        node_modules/.bin/testcafe firefox:headless tests
