name: End-to-End Tests

on:
  push:
    branches: [ default, testcafe-switch ]
  pull_request:
    branches: [ default ]

jobs:
  e2e-test:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 2
      matrix:
        python-version: ['3.7', '3.8']

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add .local path
      run: |
        echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
        echo "PIPX_HOME=$HOME/.local/pipx" >> $GITHUB_ENV
        echo "PIPX_BIN_DIR=$HOME/.local/bin" >> $GITHUB_ENV

    - name: Install Base Dependencies
      run: |
        sudo apt-get install python3-venv pipx libtesseract4 libtesseract-dev
        pipx install poetry

    - name: Install Dependencies
      run: |
        poetry install --no-dev
        yarn install

    - name: Run Tests
      run: |
        poetry config virtualenvs.in-project true
        poetry run ./test-server.sh &
        node_modules/.bin/testcafe firefox:headless tests
