name: Tests

on:
  push:
    branches: [default]
  pull_request:
    branches: [default]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Base Dependencies
        run: |
          sudo apt-get install python3-venv libtesseract4 libtesseract-dev
          pip install hatch

      - name: Install Dependencies
        run: |
          cd toja/server/frontend
          npm install

      - name: Build the UI
        run: |
          cd toja/server/frontend
          node_modules/.bin/vite build

      - name: Run Tests
        run: |
          cd tests
          docker-compose up --no-start
          docker-compose start
          hatch run test-server &
          sleep 5
          hatch run test api_tests/

  functional-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Base Dependencies
        run: |
          sudo apt-get install python3-venv libtesseract4 libtesseract-dev
          pip install hatch

      - name: Run Tests
        run: |
          cd tests
          docker-compose up --no-start
          docker-compose start
          sleep 5
          hatch run test functional_tests/

  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        browser: ["firefox:headless", "chromium:headless"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Base Dependencies
        run: |
          sudo apt-get install python3-venv libtesseract4 libtesseract-dev
          pip install hatch

      - name: Install Dependencies
        run: |
          cd toja/server/frontend
          npm install
          cd ../../../
          cd tests/e2e
          npm install

      - name: Build the UI
        run: |
          cd toja/server/frontend
          node_modules/.bin/vite build

      - name: Run Tests
        run: |
          cd tests
          docker-compose up --no-start
          docker-compose start
          hatch run test-server &
          sleep 5
          cd e2e
          ./node_modules/.bin/testcafe ${{ matrix.browser }}
